version: "3"

services:
 web:
  restart: always
  build: .
  ports:
   - "9090:9090"
  depends_on:
   - mongo
  networks:
   - aestetica
  environment:
   - NODE_ENV=production
  volumes:
   - media:/public/ 
 mongo:
  container_name: mongo
  image: mongo
  ports:
   - '27017:27017'
  volumes: 
   - aestetica:/data/db
  networks: 
   - aestetica
volumes:
 aestetica:
 media:
networks:
 aestetica
